### ISSUE TITLE
调试的相关问题

### ISSUE THREAD

**Issue by zhangbowei** [zwhu/Algorithms#4]
请问 你有使用 sourcemaps 吗？如果没有那是怎么调试的？

**Comment by zwhu** [comment]
这些代码都是用 ES6 写的，现在 nodejs 的引擎已经原生支持了，开 --harmony 选项

**Comment by zhangbowei** [comment]
这个工具能用。https://github.com/Jam3/devtool

**Comment by zwhu** [comment]
哦..
这个如果一定要调试的话，我一般都是用 webstrom 的...
